id: hl7.fhir.us.codex-ocpa
canonical: http://hl7.org/fhir/us/codex-ocpa
name: CodexOCPAIG
title: OCPA Implementation Guide
description: >-
  FHIR implementation guide project for oncology prior authorization (OCPA),
  using SUSHI for authoring and IG Publisher for guide generation.
status: draft
version: 0.1.0
releaseLabel: ci-build
fhirVersion: 4.0.1
copyrightYear: 2026+
FSHOnly: false

publisher:
  name: HL7 International / Clinical Interoperability Council
  url: http://www.hl7.org/Special/committees/cic
  email: ciclist@lists.HL7.org

menu:
  Home: index.html
  Project Documentation: docs.html
