id: hl7.fhir.us.codex-ocpa
canonical: http://hl7.org/fhir/us/codex-ocpa
name: CodexOCPAIG
title: OCPA Implementation Guide
description: >-
  FHIR implementation guide project for oncology prior authorization (OCPA),
  using SUSHI for authoring and IG Publisher for guide generation.
status: draft
version: 0.1.0
releaseLabel: ci-build
fhirVersion: 4.0.1
copyrightYear: 2026+
FSHOnly: false

publisher:
  name: OCPA Project
  url: https://example.org/ocpa

menu:
  Home: index.html
  Project Documentation: docs.html
